// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AboutController from "./about_controller"
application.register("about", AboutController)

import ContactController from "./contact_controller"
application.register("contact", ContactController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ReactController from "./react_controller"
application.register("react", ReactController)

import ServicesController from "./services_controller"
application.register("services", ServicesController)

import TestimonialsController from "./testimonials_controller"
application.register("testimonials", TestimonialsController)
